import './globals.css'
import type { Metadata } from 'next'
// eslint-disable-next-line camelcase
import { Inter, Open_Sans } from 'next/font/google'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })
const openSans = Open_Sans({ subsets: ['latin'], variable: '--font-open-sans' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${openSans.variable} font-inter`}>
        {children}
      </body>
    </html>
  )
}
